git submodule add git://github.com/vim-scripts/Color-Sampler-Pack.git bundle/Color-Sampler-Pack
git submodule add https://github.com/wincent/Command-T.git bundle/Command-T
git submodule add git://github.com/vim-scripts/ZoomWin.git bundle/ZoomWin
git submodule add git://github.com/mileszs/ack.vim.git bundle/ack.vim
git submodule add https://github.com/Raimondi/delimitMate.git bundle/delimitMate
git submodule add git://github.com/mattn/gist-vim.git bundle/gist-vim
git submodule add git://github.com/ddollar/nerdcommenter.git bundle/nerdcommenter
git submodule add git://github.com/wycats/nerdtree.git bundle/nerdtree
git submodule add git://github.com/ajf/puppet-vim.git bundle/puppet-vim
git submodule add git://github.com/vim-scripts/searchfold.vim.git bundle/searchfold.vim
git submodule add git://github.com/msanders/snipmate.vim.git bundle/snipmate.vim
git submodule add git://github.com/ervandew/supertab.git bundle/supertab
git submodule add git://github.com/scrooloose/syntastic.git bundle/syntastic
git submodule add git://github.com/vim-scripts/taglist.vim.git bundle/taglist.vim
git submodule add git://github.com/timcharper/textile.vim.git bundle/textile.vim
git submodule add https://github.com/tsaleh/vim-align.git bundle/vim-align
git submodule add https://github.com/t9md/vim-chef.git bundle/vim-chef
git submodule add git://github.com/kchmck/vim-coffee-script.git bundle/vim-coffee-script
git submodule add git://github.com/altercation/vim-colors-solarized.git bundle/vim-colors-solarized
git submodule add git://github.com/tpope/vim-cucumber.git bundle/vim-cucumber
git submodule add git://github.com/tpope/vim-endwise.git bundle/vim-endwise
git submodule add git://github.com/tpope/vim-fugitive.git bundle/vim-fugitive
git submodule add git://github.com/tpope/vim-git.git bundle/vim-git
git submodule add git://github.com/tpope/vim-haml.git bundle/vim-haml
git submodule add git://github.com/michaeljsmith/vim-indent-object.git bundle/vim-indent-object
git submodule add git://github.com/wgibbs/vim-irblack.git bundle/vim-irblack
git submodule add git://github.com/pangloss/vim-javascript.git bundle/vim-javascript
git submodule add git://github.com/tpope/vim-markdown.git bundle/vim-markdown
git submodule add git://github.com/tpope/vim-ragtag.git bundle/vim-ragtag
git submodule add git://github.com/tpope/vim-rails.git bundle/vim-rails
git submodule add git://github.com/taq/vim-rspec.git bundle/vim-rspec
git submodule add git://github.com/bdd/vim-scala.git bundle/vim-scala
git submodule add git://github.com/tpope/vim-surround.git bundle/vim-surround
git submodule add git://github.com/tpope/vim-unimpaired.git bundle/vim-unimpaired
git submodule add git://github.com/tpope/vim-vividchalk.git bundle/vim-vividchalk
